src/regel/urls.py
from django.urls import path
from regel.views import (
    RegelListeView,
    RegelHinzufuegenView,
    RegelFehlerView,
    RegelDetailView,
    RegelBearbeitenView,
    RegelEntfernenView,
)

#URL Dispatch für Regel-App

app_name    = 'regel'
urlpatterns = [
    path('',                     RegelListeView.as_view(),       name='regel-liste'),
    path('hinzufuegen/',         RegelHinzufuegenView.as_view(), name='regel-hinzufuegen'),
    path('fehler/',              RegelFehlerView.as_view(),      name='regel-fehler'),
    path('<int:id>/',            RegelDetailView.as_view(),      name='regel-details'),
    path('<int:id>/bearbeiten/', RegelBearbeitenView.as_view(),  name='regel-bearbeiten'),
    path('<int:id>/entfernen/',  RegelEntfernenView.as_view(),   name='regel-entfernen'),
    
]

src/trading/urls.py
from account.views import (
    registration_view,
    logout_view,
    login_view,
    account_view,
    account_edit_view,
)

from django.conf.urls.static import static
from django.contrib          import admin
from django.urls             import include, path
from django.views.generic    import TemplateView


#allgemeiner URL Dispatch für TechTrader

urlpatterns = [
    #Adminseite, Zugang nur mit superuser
    path('admin/', admin.site.urls),

    #Allgemein zugängliche Seiten
    path('',       TemplateView.as_view(template_name = "home.html"),  name = "home-view"),
    path('home/',  TemplateView.as_view(template_name = "home.html"),  name = "home-view"),
    path('about/', TemplateView.as_view(template_name = "about.html"), name = "about"),
    

    # Seiten für User Management
    path('registrieren/',      registration_view, name = "registrierung-view"),
    path('logout/',            logout_view,       name = "logout-view"),
    path('login/',             login_view,        name = "login-view"),
    path('profil/',            account_view,      name = "profil-view"),
    path('profil/bearbeiten/', account_edit_view, name = "bearbeiten-view"),

    #TechTrader Apps
    path('simulationen/', include('simulation.urls'), name = "simulationen-app"),
    path('strategien/',   include('strategie.urls'),  name = "strategien-app"),
    path('regeln/',       include('regel.urls'),      name = "regeln-app"),
    path('indikatoren/',  include('indikator.urls'),  name = "indikatoren-app"),
]

src/templates/modulViews/generisch_Elemente/drag_and_drop.html
<label>Verwendete Regeln</label>
<section class = "container emptycontainer" > 
    <div class = "reminderwennleer">
        <p> Füge Regeln per Drag and Drop  hinzu.</p> 
    </div> 
</section>
<label>Verfügbare Regeln</label>

<section class = "container"> 
    <div class = "reminderwennleer" >
        <p >Keine Regeln vorhanden</p> 
    </div> 
    {% for regel in regeln %}
    <div class = "draggable" draggable = "true">
            <div class = "dnd_reihenfolgennummer">{{forloop.counter}}</div> 
            <div class = "dnd_id">Regel-ID: {{regel.id}} </div> <br/>
            <div class = "dnd_name">Name: {{regel.name}}</div>
            <div class = "dnd_beschreibung">Beschreibung: {{regel.beschreibung}}</div>
    </div> 
     
    {%endfor%}
</section> 

src/templates/modulViews/generisch_Elemente/generisch_formular.html
{% if appName == "strategie" %}
    {% block style %}
        {%load static%} 
        <link rel = "stylesheet" href = "{% static 'drag-and-drop.css' %}">
    {% endblock %} 

    {% block skripte %}
        <script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>
        <script src="{% static 'drag-and-drop.js' %}" defer></script> 
    {% endblock %} 
{% endif %}

{% if appName == "strategie" %}
    <form action = "." method = "post" onsubmit = "ausgewählteRegelnSpeichern()"> {% csrf_token %}

        {{form.as_p}}  

        {% include './drag_and_drop.html'%}

        
{% else %} 
    <form action = "." method = "post"> {% csrf_token %}

        <label class = "labelspan">Name :</label>
        {{form.name}}

        <label class = "labelspan">Beschreibung :</label>
        {{form.beschreibung}}

        {% if appName == "indikator" %}
            <label class = "labelspan">Code :</label>
            {{form.berechnung_pseudo_code}}
            {{form.eigene_skala}}
            <label class = "labelspan">Eigene Skala verwenden?</label>
        {% endif %}

        {% if appName == "regel" %}
            <label class = "labelspan">Code :</label>
            {{form.berechnung_pseudo_code}}
            
        {% endif %}    
{% endif %}

src/templates/modulViews/generisch_Elemente/generisch_objekt_daten.html
<span class = "labelspan" >Beschreibung</span>
    <p class = "objektinformation">{{object.beschreibung}}</p> 

<span class = "labelspan" >Code</span>
    {% autoescape off %}
        <p>{{object.berechnung_pseudo_code|linebreaks}}</p>
    {% endautoescape %}

{%if appName == "indikator" %}
    <span class = "labelspan">Hat eigene Skala</span>
    {%if object.eigene_skala%}
        <p> Ja </p>
    {%else%}
        <p> Nein </p> 
    {%endif%}
    
{% endif %}

src/templates/modulViews/generisch_Elemente/generisch_strategie_daten.html
<span class = "labelspan">Beschreibung</span>
    <p class = "objektinformation">{{object.beschreibung}}</p>
<span class = "labelspan">Verwendete Regeln</span>
<p></p>


<p> * globale Objekte </p>
<table>
    <colgroup>
        <col span = "1" style = "width: 7;">
        <col span = "1" style = "width: 30%;">
        <col span = "1" style = "width: 63%;">
    </colgroup>
    <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Beschreibung</th>
    </tr>
    {% for regel in verwendeteRegeln%}
        {%if regel.benutzer_id == "superuser" %}
            <tr class = 'clickable-row' data-href = "{% url 'regel:regel-details' id=regel.id %}"> 
                <td>{{regel.id}}*</td>
                <td>{{regel.name}}</td>
                <td>{{regel.beschreibung}}</td>
            </tr>
        {%else%}
            <tr class = 'clickable-row' data-href = "{% url 'regel:regel-details' id=regel.id %}"> 
                <td>{{regel.id}}</td>
                <td>{{regel.name}}</td>
                <td>{{regel.beschreibung}}</td>
                </tr>
        {%endif%}
    {%endfor%}
</table> 

<script>
    jQuery(document).ready(function($) {
        $("table tr").hide();
        $("table tr").each(function(index){
          $(this).delay(index*100).show(500);
        });
      $(".clickable-row").click(function() {
          window.location = $(this).data("href");
      });
    });
</script>